Add missing headers for C++23
Add headers to resolve C++23 build errors because C++23 removed
transitive includes so you have to add the headers directly.

Errors:
device/generic/goldfish/hals/audio/talsa.cpp:109:13: error: use of
undeclared identifier 'sscanf'
  109 |     return (sscanf(propValue, "%u", &value) == 1) ? value :
defaultValue
device/generic/goldfish/hals/audio/primary_device.cpp:49:9: error: use
of undeclared identifier 'isnan'
   49 |     if (isnan(volume) || volume < 0 || volume > 1.0) {
device/generic/goldfish/hals/audio/stream_out.cpp:410:9: error: use of
undeclared identifier 'isnan'
  410 |     if (isnan(left) || left < 0.0f || left > 1.0f
device/generic/goldfish/hals/audio/stream_out.cpp:411:44: error: use of
undeclared identifier 'isnan'
  411 |         || right < 0.0f || right > 1.0f || isnan(right)) {

Flag: EXEMPT BUGFIX
Bug: 429048222
Test: m android.hardware.audio@7.1-impl.ranchu
Change-Id: Ia9a150a6c555ea7cfabfbed6c20fbc0db1fe3569