Enable picture_in_picture feature
Fix the following error:
04-21 14:10:14.671  7610  7610 E AndroidRuntime: java.lang.RuntimeException:
Unable to start activity ComponentInfo{android.server.cts/android.server.cts.PipActivity}:
java.lang.IllegalStateException: enterPictureInPictureMode:
Device doesn't support picture-in-picture mode

BUG: 37574631

Test:
run cts -m CtsServicesHostTestCases -t
android.server.cts.ActivityManagerAssistantStackTests#testAssistantStackZOrder

Change-Id: I184c906cb5d01e5a2365c38446768a0e37a2cac6