Add missing headers for C++23
Add headers to resolve C++23 build errors because C++23 removed
transitive includes so you have to add the headers directly.

Errors:
device/generic/goldfish/hals/camera/CameraDevice.cpp:58:10: error: no
member named 'sort' in namespace 'std'
   58 |     std::sort(keys.begin(), keys.end());

Flag: EXEMPT BUGFIX
Bug: 429048222
Test: m android.hardware.camera.provider.ranchu_minigbm
Change-Id: I9f791f665de7652a201fabf6fef1937b5f25ddb2